server:
  port: 9003


spring:
  main:
    allow-bean-definition-overriding: true  #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 1111111

    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化
    initialSize: 3
    # 最大
    maxActive: 20
    # 最小
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

  # http
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # 文件上传大小
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 一次传多个文件的总大小
      max-request-size: 100MB

  #redis
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    port: 6379
    password: 111111
    timeout: 5000ms

    jedis:
      pool:
        # 连接池中的最大连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  # 取消spring对freemarker默认templates目录的检测
  freemarker:
    check-template-location: false

###   Mybatis Config  ###
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0


# 日志
logging.config: classpath:logging-spring.xml
swagger:
  title: 接口文档
  basepackage: com.security.learn3
  version: 1.0.0


janche:
  pagesize: 5
  #  排序属性
  sortcolumn:  id
  #  排序规则 1 升序  2 降序
  sorttype: 1
  # 跨域ip处理
  origins: http://localhost:8080,http://192.168.99.100:8091,http://127.0.0.1:8080,http://cebon.hoteas.com:8082

  jwt:
    secret: janche
    ttl: 600000
    remember: 604800000


custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/login"
        - "/logout"
        - "/refresh/token"
      # options的请求不拦截
      options:
        - "/**"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"
        - "/css/**"
        - "/js/**"
        - "/images/**"
        - "/fonts/**"
        - "/favicon.ico"
        - "/static/**"
        - "/resources/**"
        - "/error"
        - "/status/*"
        - "/swagger-ui.html"
        - "/v2/**"
        - "/webjars/**"
        - "/swagger-resources/**"